# Generated by Django 4.0.1 on 2022-01-11 04:11

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Update date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('image', stdimage.models.StdImageField(upload_to='products', verbose_name='Image')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
